/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.bopre.support.generator.core

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
